name: Test gitsum

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
        pip install -r requirements.txt
    - name: Grant execution permission
      run: |
        chmod +x gitsum
      if: ${{ runner.os != 'Windows' }}
    - name: Test with pytest
      run: |
        pytest
    # Manually debug failing pipeline
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && failure() }}
    - name: Report test coverage
      run: |
        coverage report
        coverage json
    - name: Read coverage.json
      id: read_coverage
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'coverage.json'
          prop_path: 'totals.percent_covered_display'
    - name: Create code coverage badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: cc9f4d1c6c0152b11b3eb2fe84fc0076
        filename: gitsum-coverage.json
        label: Test coverage
        message: "92%"
        minColorRange: 50
        maxColorRange: 90
