name: Test gitsum

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
        pip install -r requirements.txt
    - name: Grant execution permission
      if: ${{ runner.os != 'Windows' }}
      run: |
        chmod +x gitsum
    - name: Test with pytest
      run: |
        pytest
    # Manually debug failing pipeline
    - name: Setup tmate session
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && failure() }}
      uses: mxschmitt/action-tmate@v3
    - name: Report test coverage
      run: |
        coverage report
        coverage json
    # Generate test coverage
    # Do this on Ubuntu because that's usually the fastest build
    - name: Read coverage display
      if: ${{ runner.os == 'Linux' }}
      id: read_coverage_display
      uses: notiz-dev/github-action-json-property@v0.2.0
      with: 
          path: 'coverage.json'
          prop_path: 'totals.percent_covered_display'
    - name: Read coverage percent
      if: ${{ runner.os == 'Linux' }}
      id: read_coverage_percent
      uses: notiz-dev/github-action-json-property@v0.2.0
      with: 
          path: 'coverage.json'
          prop_path: 'totals.percent_covered'
    - name: Create code coverage badge
      if: ${{ runner.os == 'Linux' }}
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: cc9f4d1c6c0152b11b3eb2fe84fc0076
        filename: gitsum-coverage.json
        label: Test coverage
        message: ${{ format('{0}%', steps.read_coverage_display.outputs.prop) }}
        valColorRange: ${{ steps.read_coverage_percent.outputs.prop }}
        minColorRange: 50
        maxColorRange: 90
    - name: Create platorm-specific build status badge (success)
      if: ${{ success() }}
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: cc9f4d1c6c0152b11b3eb2fe84fc0076
        filename: ${{ format('gitsum-{0}.json', runner.os) }}
        label: ${{ format('{0} build', runner.os) }}
        message: 'Passed'
        color: 'success'
    - name: Create platorm-specific build status badge (failure)
      if: ${{ failure() }}
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: cc9f4d1c6c0152b11b3eb2fe84fc0076
        filename: ${{ format('gitsum-{0}.json', runner.os) }}
        label: ${{ format('{0} build', runner.os) }}
        message: 'Failed'
        color: 'red'
