name: Test gitsum

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -r test-requirements.txt
    - name: Build project
      run: |
        python -m build
    - name: Install package
      run: |
        pip install --find-links=dist gitsum
    - name: Test with pytest
      run: |
        pytest
    # Manually debug failing pipeline
    - name: Setup tmate session
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && failure() }}
      uses: mxschmitt/action-tmate@v3
    - name: Report test coverage
      run: |
        coverage report
        coverage json
